
# Source type topics need to be changed to your needs
topic_estimated_source_pose: "base_link_pf"
topic_estimated_target_path: "estimated_path"

topic_ground_truth_source_pose: "/ground_truth_broadcaster/pose"  
topic_ground_truth_target_path: "real_path"

#//TODO find better way then with integers
# enum SOURCE_TYPE{
#     POSE = 0,
#     POSESTAMPED = 1,
#     ODOMETRY = 2
# };
estimation_source_type: 1  #Here we expected our source type to be geometry_msgs::PoseStamped
ground_truth_source_type: 1

